# Server port is arbitrary
server:
  port: 8082
# Data Source Setup
# Note: Users must create a mysql db that they will reference here, create a user that has access to it on localhost
#       and provide the credentials below to access it
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/critter
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: embedded
  # uncomment the below lines to view sql output in console
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none